# Generated by Django 3.0.6 on 2021-06-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_phone',
            field=models.CharField(default=966542207269, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('start_time', 'date', 'table')},
        ),
    ]
